#!/bin/python3

from sys import exit
from subprocess import check_output
from os import path
import re

acpi = check_output(['acpi', '-b']).decode('utf-8')

if 'rate information unavailable' in acpi:
    exit(1)

p = re.compile(r": (\w+), (\d+)%")
m = p.search(acpi)
status = m.group(1)
percent = m.group(2)

if status == 'Discharging':
    print_status = '▽'
elif status == 'Charging':
    print_status = '△'
else:
    print_status = '⬙'

if 'harging' not in status or not path.exists('/tmp/.bloat'):
    time = ""
else:
    time = " {} ".format(re.compile(r', (\d\d:\d\d)').search(acpi).group(1))

if status == 'Discharging':
    percent = int(percent)
    if percent < 20:
        c = r"#FF0000"
    elif percent < 40:
        c = r"#FFAE00"
    elif percent < 60:
        c = r"#FFF600"
    elif percent < 85:
        c = r"#A8DD00"
    else:
        c = '-'
else:
    c = '-'

if c != '':
    clear = '%{F-}'
else:
    clear = ''
fore = '%{{F{}}}'.format(c)
under = '%{{U{}}}'.format(c)
print("{}%{{+u}}%{{F#FFFF00}}⚡%{{F-}}{}{}{}{}{}%{{U-}}%{{-u}}".format(under, fore, percent, print_status, time, clear))
