#!/bin/bash

bluetoothctl devices | cut -f2 -d' ' | xargs -L 1 bluetoothctl info | awk '
$1 == "Name:"  { $1 = ""; sub(/^[ \t]+|[ \t]+$/, ""); name = $0; }
$1 == "Connected:" && $2 == "yes" { devices = (devices == "") ? name : devices " [&] " name }
END { if (devices != "") print(devices) }
'
