#!/bin/sh
# shellcheck disable=SC2119

# shellcheck source=/home/mendess/Projects/spell-book/spells/library.spell
. library


CURRENT="$(m current \
    | head -2 \
    | tail -1 \
    | cut -d ':' -f2 \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

if [ -e /tmp/.bloat ]; then
    TRUNC=22
    CURRENT="$(echo "$CURRENT" | sed -r 's/^(.{'"$TRUNC"'}).*/\1.../')"
fi

[ -z "$CURRENT" ] && echo && exit 0

case $BLOCK_BUTTON in
    1) m prev-file ;;
    2) m pause ;;
    3) m next-file ;;
    4) m vu 5 ;;
    5) m vd 5 ;;
esac

case $(echo '{"command":["get_property","pause"]}' | socat - "$(mpvsocket)" | jq .data -r) in
    true) SIGIL='││' ;;
    false) SIGIL='⊳' ;;
esac

VOL="$(echo '{ "command": ["get_property", "volume"] }' \
    | socat - "$(mpvsocket)" \
    | jq -r .data)"

echo "♪" "$CURRENT" "$SIGIL" "$VOL%" "♪"
