#!/bin/bash

set -euo pipefail

command -V wg-quick &>/dev/null || exit 0

GREEN="#55AA00"
RED="#FF2200"
UG="%{U$GREEN}"
UR="%{U$RED}"
FG="%{F$GREEN}"
FR="%{F$RED}"
FRST="%{F$LEMON_FG}"

paint() {
    printf "%%{r}%s%s%s" "$1" "$2" "$3"
}

ip -color=never -o -d link show |
    awk '/wireguard/ {print $2}' |
    tr -d : |
    while read -r network; do
        fst_address=$(ip -color=never -o -d address |
            grep "$network" |
            grep -o -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+' |
            cut -d/ -f1 |
            sed -E 's/\.[0-9]+$/.1/')
        printf " "
        if ping -w 1 -c 1 "$fst_address" &>/dev/null; then
            paint "$UG" "$FG" "["
            paint "$UG" "$FRST" "$network"
            paint "$UG" "$FG" "]"
        else
            paint "$UR" "$FR" "["
            paint "$UR" "$FRST" "$network"
            paint "$UR" "$FR" "]"
        fi
    done

echo
