#!/bin/bash
declare -A focus_cmds
get_cmd() {
    [[ "${focus_cmds[$1]}" ]] ||
        focus_cmds["$1"]="$(herbstclient list_keybinds |
            grep -F "Mod4+$1" |
            cut -f2- |
            tee /dev/stderr)"
    echo "${focus_cmds[$1]}"
}
hc=herbstclient
while
    # shellcheck disable=1091
    . "$(dirname "$0")/workspaces_colors"
    wm=
    i=0
    while IFS=$'\n' read -r t; do
        [[ "$t" ]] || continue
        i=$(((i + 1) % 10))
        name=${t:1:${#t}}
        case "$t" in
            .*) # empty unfocused
                continue
                ;;
            -* | %*) # not on this monitor
                continue
                ;;
            :*) # occupied unfocused
                FG=$COLOR_OCCUPIED_FG
                BG=$COLOR_OCCUPIED_BG
                UL=$COLOR_OCCUPIED_UL
                ;;
            +*) # occupied active
                FG=$COLOR_ACTIVE_OCCUPIED_FG
                BG=$COLOR_ACTIVE_OCCUPIED_BG
                UL=$COLOR_ACTIVE_OCCUPIED_UL
                ;;

            \#*) # focused
                FG=$COLOR_FOCUSED_OCCUPIED_FG
                BG=$COLOR_FOCUSED_OCCUPIED_BG
                UL=$COLOR_FOCUSED_OCCUPIED_UL
                ;;
            !*) # urgent
                FG=$COLOR_URGENT_FG
                BG=$COLOR_URGENT_BG
                UL=$COLOR_URGENT_UL
                ;;
        esac
        [[ "$($hc attr tags.by-name."$name".my_monitor)" != "$LEMON_MONITOR" ]] &&
            continue
        colors="%{F${FG}}%{B${BG}}%{U${UL}}%{+u}"
        focus_cmd=$(get_cmd "$i")
        actions="%{A1:$hc $focus_cmd:}%{A2:$hc $focus_cmd:}"
        end="%{A}%{A}%{U-}%{B-}%{F-}%{-u}"
        wm="${wm}${colors}${actions} $name ${end}"
    done < <(herbstclient tag_status "$LEMON_MONITOR" | tr '\t' '\n')
    echo "${wm}"
    read -r _
do
    :
done < <(herbstclient -i 'tag_changed|tag_flags|tag_added|tag_removed|tag_renamed')
