#!/bin/bash

#sxhkd &

i=1
for monitor in $(bspc query -M); do
    bspc monitor "$monitor" \
            -n "$i" \
            -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    (( i++ ))
done
unset i

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr
bspc rule -a floating-terminal state=floating
bspc rule -a feh state=floating

bar() {
    while :;
    do
        echo "$(.config/bspwm/media)" \
            "$(.config/bspwm/brightness)" \
            "$(.config/bspwm/disk)" \
            "$(.config/bspwm/iface)" \
            "$(.config/bspwm/wifi)" \
            "$(.config/bspwm/load_average)" \
            "$(.config/bspwm/memory)" \
            "⚡$(.config/bspwm/battery)" \
            "$(date +"%d/%m %H:%M")"
        sleep 10
    done
}

killall sxhkd polybar

sxhkd &
polybar example &
