#!/bin/bash

case "$(hostname)" in
    weatherlight)
        bspc monitor -d 1 2 3 4 5 6 7 8 9 A
        ;;
    tolaria)
        bspc monitor ^1 -d 1 2 3 4 5
        bspc monitor ^2 -d 6 7 8 9 A
        ;;
esac

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config remove_unplugged_monitors true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr
bspc rule -a floating-terminal state=floating
bspc rule -a feh state=floating
bspc rule -a URxvt state=floating
bspc rule -a Sxiv state=floating
bspc rule -a my-media-player desktop=^10
bspc rule -a Zathura state=tiling

bar() {
    while :;
    do
        echo "$(.config/bspwm/media)" \
            "$(.config/bspwm/brightness)" \
            "$(.config/bspwm/disk)" \
            "$(.config/bspwm/iface)" \
            "$(.config/bspwm/wifi)" \
            "$(.config/bspwm/load_average)" \
            "$(.config/bspwm/memory)" \
            "⚡$(.config/bspwm/battery)" \
            "$(date +"%d/%m %H:%M")"
        sleep 10
    done
}

if ! pgrep sxhkd
then
    sxhkd > ~/.sxhkd.log &
else
    pkill -USR1 -x sxhkd
    :> ~/.sxhkd.log
    # sxhkd > ~/.sxhkd.log &
fi

if ! pgrep polybar
then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload example &
    done
fi
