#!/bin/bash
image() {
    echo "$1 -> $TEMPFILE"
    dl "$1" >"$TEMPFILE" || return
    case "$(file "$TEMPFILE")" in
        *Web/P* | *SVG*)
            convert "$TEMPFILE" "$TEMPFILE.png" &&
                rm -f "$TEMPFILE" &&
                TEMPFILE="$TEMPFILE.png" ||
                return
            ;;
    esac
    size="$(file "$TEMPFILE" | sed -E 's/.* ([0-9]+)\s*x\s*([0-9]+).*/\1x\2/')"
    w=${size%x*}
    h=${size#*x}
    if [[ "$h" -gt 1000 ]]; then
        w=$(((w * 1000) / h))
        h=1000
    fi
    if [[ "$w" -gt 1800 ]]; then
        h=$(((h * 1800) / w))
        w=1800
    fi
    sxiv -b -g "${w}x${h}" "$TEMPFILE"
}

text() {
    dl "$1" >"$TEMPFILE" && $TERMINAL -e bash -c "$EDITOR '$TEMPFILE'"
}

pdf() {
    dl "$1" | zathura -
}

video() {
    notify 'Playing in mpv' "$1" -u low
    mpv "$1" || {
        notify 'Retrying in mpv' "$1" -u low
        mpv "$1"
    }
}

gif() {
    notify 'Playing in mpv' "$1" -u low
    mpv --loop-file "$1"
}

git() {
    notify 'opening from github' "$1" -u low
    dl "$1" >"$TEMPFILE" || return
    app=$(xdg-mime query default "$(xdg-mime query filetype "$TEMPFILE")")
    # if the app is not vim, then the fallback at the end of the case will be used
    if [[ "$app" = *vim.desktop ]]; then
        $TERMINAL -e bash -c "$EDITOR '$TEMPFILE'"
    else
        xdg-open "$TEMPFILE"
    fi
}

archive() {
    dl "$1" >"$TEMPFILE" || return
    $TERMINAL -e bash -c "
    select open in $EDITOR extract; do
        case \$open in
            $EDITOR)
                $EDITOR $TEMPFILE
                ;;
            extract)
                read -r -e -p 'Where to extract? '
                target=\"\${REPLY:-.}\"
                if [ -e \"\$target\" ]; then
                    if [ ! -d \"\$target\" ]; then
                        target=\"\$(basename \"\$target\")\"
                    fi
                else
                    mkdir -p \"\$target\" || exit
                fi
                mv \"\$target\" '$TEMPFILE'
                cd \"\$target\"
                ex '$TEMPFILE'
                ;;
        esac
    done"
}
