xrdb -merge ~/.config/X11/Xresources
# deamons
changeMeWallCicle &
clean_ws_names.spell &
picom --experimental-backends --daemon
dropbox start &
battery_check &
dunst &
clipmenud &
nmcli -t dev | grep 'ethernet:unavailable' && nm-applet &
calcurse --daemon -C "$XDG_CONFIG_HOME"/calcurse -D "$XDG_DATA_HOME"/calcurse

# Settings
setxkbmap -option caps:escape
if [ "$(cat /etc/hostname)" = tolaria ]; then
    xrandr --output DP-5 --mode 1920x1080  --primary \
        --output HDMI-0 --auto --left-of DP-5
    xmodmap -e 'keycode  21 = plus equal plus equal'
fi
rm -f /tmp/bspwm_log
exec bspwm
# exec dbus-launch leftwm
