changeMeWallCicle &
compton -I 1 -O 1 --config $HOME/.config/compton.conf -b
dropbox start &
battery_check_cicle &
dunst &
setxkbmap -option caps:escape
if [ "$(hostname)" = tolaria ]
then
    xrandr --output DVI-D-0 --mode 1920x1080 --rate 120  --rotate normal --primary
    xmodmap -e 'keycode  21 = plus equal plus equal'
fi
calcurse --deamon
nmcli -t dev | grep 'ethernet:unavailable' && nm-applet &
wmname compiz
exec bspwm
