#!/bin/bash
export RTV_EDITOR='nvim'
export VISUAL='nvim'
export EDITOR='nvim'
export BROWSER="firefox"
export WWW_HOME='duckduckgo.com/lite'

export PATH=$PATH:~/.local/bin
export PATH=$PATH:~/.cargo/bin
export PAGER="less"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export LESS_TERMCAP_mb=$'\e[1;35m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;32m'
export SPELLS="$(dirname "$(dirname "$(readlink ~/.zprofile)")")"

if [ "$(tty)" = "/dev/tty1" ]; then
    toilet -f mono9 -F metal "Starting i3"
    pgrep i3 || startx 2> /dev/null
    clear
elif [ "$(tty)" = "/dev/tty2" ]; then
    toilet -f mono9 -F metal "            Starting dwm  "
    pgrep dwm || startx /usr/local/bin/dwm
elif [[ $(tty) == *"tty"* ]]; then
    tmux new-session -s "$(basename "$(tty)")"
fi
