#!/bin/bash
#shellcheck disable=1091
#shellcheck disable=1090

[[ $- != *i* ]] && return

export HISTSIZE=""
PROMPT_COMMAND='history -a;history -n;stty susp ^@'
export HISTCONTROL='ignoredups'
shopt -s histappend
shopt -s histverify
shopt -s autocd
shopt -s checkwinsize
stty -ixon
set -o noclobber

bind "set completion-ignore-case On"
bind "set show-all-if-unmodified on"
bind -x '"\C-z":"fg"'
for i in - {0..9} ; do
    bind -r '\e'$i
done

GPG_TTY="$(tty)"
export GPG_TTY

if [ -z "$SPELLS" ]
then
    tmp="$(dirname "$(dirname "$(dirname "$(readlink "$HOME"/.bash_profile)")")")"
    export SPELLS="$tmp"
    unset tmp
fi

for f in "$SPELLS"/runes/bash/*.bash
do
    source "$f"
done
[ -e /usr/share/nvm/init-nvm.sh ] && source /usr/share/nvm/init-nvm.sh

[ -f ~/.config/broot/launcher/bash/br ] && source ~/.config/broot/launcher/bash/br
:
