#!/bin/bash


[[ $- != *i* ]] && return

export HISTSIZE=""
PROMPT_COMMAND='history -a;history -n'
export HISTCONTROL='ignoredups'
shopt -s histappend
shopt -s histverify
set -o noclobber

bind "set completion-ignore-case On"
bind "set show-all-if-unmodified on"
GPG_TTY="$(tty)"
export GPG_TTY

if [ -z "$SPELLS" ]
then
    tmp="$(dirname "$(dirname "$(dirname "$(readlink "$HOME"/.bash_profile)")")")"
    export SPELLS="$tmp"
    unset tmp
fi

for f in "$SPELLS"/runes/bash/*.bash
do
    #shellcheck disable=SC1090
    source "$f"
done

#shellcheck source=/home/mendess/projects/spell-book/spells/library.spell
source "$SPELLS"/spells/library.spell

echo "Dear Pedro,  you are the best boyfriend ever and I love you very much.
 I would like you give you something you love bur virtually." && sleep 5 && sxiv somethingyoulike.jpg
