#!/bin/bash

export RTV_EDITOR='nvim'
export VISUAL='nvim'
export EDITOR='nvim'
export BROWSER="firefox"
export WWW_HOME='duckduckgo.com/lite'
export TERMINAL='alacritty'
export _JAVA_AWT_WM_NONREPARTENTING=1

export PAGER="less"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export LESS_TERMCAP_mb=$'\e[1;35m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;32m'
SPELLS=""
# tem de existir para existir, e existe por acaso
SPELLS="$(dirname "$(dirname "$(dirname "$(readlink "$HOME"/.bash_profile)")")")"
export SPELLS

# FZF
export FZF_DEFAULT_OPTS='
--height 40%
--preview '\''(bat --color always --style plain {} || cat {} || tree -C {}) 2>/dev/null '
export FZF_CTRL_R_OPTS='--no-sort'

# home cleanup
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"

#shellcheck source=/home/mendess/.config/user-dirs.dirs
. ~/.config/user-dirs.dirs

export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export LESSHISTFILE=-
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export WEECHAT_HOME="$XDG_CONFIG_HOME"/weechat
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
#echo hsts-file \= "$XDG_CACHE_HOME"/wget-hsts >> "$XDG_CONFIG_HOME/wgetrc"
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
[ -z "$SSH_CLIENT" ] && export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export HISTFILE="$XDG_CACHE_HOME/bash_history"
local_bin=
local_bin=$(find ~/.local/bin -type d | sed 's|/$||'| tr '\n' ':')
export PATH="$local_bin:$PATH"
export PATH="$CARGO_HOME/bin":$PATH
[ -e ~/.shortcuts ] && export PATH=~/.shortcuts:$PATH
# hash weechat &>/dev/null && alias weechat='weechat -d $XDG_CONFIG_HOME/weechat'
# hash calcurse &>/dev/null && alias calcurse='calcurse -C "$XDG_CONFIG_HOME"/calcurse -D "$XDG_DATA_HOME"/calcurse'
# hash firefox &>/dev/null && alias firefox='HOME="$XDG_DATA_HOME" firefox'

#shellcheck source=/home/mendess/.bashrc
[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ "$(tty)" = "/dev/tty1" ]; then
    readonly pfetch="$(command -v pfetch)"
    $pfetch
    rm -f /tmp/startx.log
    pgrep bspwm || xinit -- :0 vt1 &> /tmp/startx.log
elif [[ "$(tty)" == *"tty"* ]] && [[ "$(tty)" != '/dev/tty2' ]] && hash tmux 2>/dev/null; then
    tmux new-session -s "$(basename "$(tty)")"
fi
