#!/bin/bash

export RTV_EDITOR='nvim'
export VISUAL='nvim'
export EDITOR='nvim'
export BROWSER="firefox"
export WWW_HOME='duckduckgo.com/lite'

export PATH=~/.local/bin:$PATH
export PATH=~/.cargo/bin:$PATH
export PAGER="less"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export LESS_TERMCAP_mb=$'\e[1;35m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;32m'
SPELLS=""
SPELLS="$(dirname "$(dirname "$(dirname "$(readlink "$HOME"/.bash_profile)")")")"
export SPELLS

mpvsocket() {
    if [ -e /tmp ]
    then
        prefix=/tmp
    else
        prefix=~
    fi
    #shellcheck disable=SC2009
    last=$(ps -ef | grep -oP 'mpvsocket[0-9]*' | sort | uniq | tail -1)
    if [ -z "$last" ]
    then
        if [ "$2" = new ]
        then
            echo "$prefix/.mpvsocket0"
        else
            echo "/dev/null"
        fi
    else
        if [ "$2" = new ]
        then
            echo "$prefix/.mpvsocket$(( $(echo "$last" | grep -oP '[0-9]+$') + 1 ))"
        else
            echo "$prefix/$last"
        fi
    fi
}

#shellcheck source=/home/mendess/.bashrc
[[ -f ~/.bashrc ]] && . ~/.bashrc >/dev/null

if [ "$(tty)" = "/dev/tty1" ]; then
    toilet -f mono9 -F metal "Starting i3"
    pgrep i3 || startx 2> /dev/null
    clear
elif [[ $(tty) == *"tty"* ]] && [[ $(tty) != '/dev/tty2' ]]; then
    tmux new-session -s "$(basename "$(tty)")"
fi
