#!/bin/bash

export RTV_EDITOR='nvim'
export VISUAL='nvim'
export EDITOR='nvim'
export BROWSER="firefox"
export WWW_HOME='duckduckgo.com/lite'

export PATH=~/.local/bin:$PATH
export PATH=~/.cargo/bin:$PATH
[ -e ~/.shortcuts ] && export PATH=~/.shortcuts:$PATH
export PAGER="less"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export LESS_TERMCAP_mb=$'\e[1;35m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;32m'
SPELLS=""
# tem de existir para existir, e existe por acaso
SPELLS="$(dirname "$(dirname "$(dirname "$(readlink "$HOME"/.bash_profile)")")")"
export SPELLS

# FZF
export FZF_DEFAULT_OPTS='
--height 40%
--preview '\''(bat --color always --style plain {} || cat {} || tree -C {}) 2>/dev/null '
export FZF_CTRL_R_OPTS='--no-sort'

#shellcheck source=/home/mendess/.bashrc
[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ "$(tty)" = "/dev/tty1" ]; then
    toilet -f mono9 -F metal "Booting bspwm"
    pgrep bspwm || startx &> /tmp/startx.log
elif [[ "$(tty)" == *"tty"* ]] && [[ "$(tty)" != '/dev/tty2' ]] && hash tmux 2>/dev/null; then
    tmux new-session -s "$(basename "$(tty)")"
fi
