#!/bin/bash
case "$(bspc query -M | wc -l)" in
    1)
        bspc monitor -d 1 2 3 4 5 6 7 8 9 0
        ;;
    2)
        case "$(hostname)" in
            tolaria)
                bspc monitor -o DVI-D-0 DVI-I-1
                bspc monitor ^1 -d 1 2 3 4
                bspc monitor ^2 -d 5 6 7 8 9 0
                ;;
            weatherlight)
                bspc monitor ^1 -d 1 2 3 4 5
                bspc monitor ^2 -d 6 7 8 9 0
                ;;
            *)
                bspc monitor ^1 -d 1 2 3 4 5 6 7 8
                bspc monitor ^2 -d 9 0
                ;;
        esac
        ;;
    3)
        bspc monitor ^1 -d 1 2 3
        bspc monitor ^2 -d 4 5 6
        bspc monitor ^3 -d 7 8 9 0
        ;;
    4)
        bspc monitor ^1 -d 1
        bspc monitor ^2 -d 2 3 4
        bspc monitor ^3 -d 5 6 7
        bspc monitor ^4 -d 8 9 0
        ;;
esac

if [[ "$(hostname)" = tolaria ]]; then
    bspc config window_gap 10
    bspc config border_width 5
else
    bspc config window_gap 4
    bspc config border_width 3
fi

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config remove_unplugged_monitors true
bspc config top_padding 22
bspc config ignore_ewmh_fullscreen enter
bspc config ignore_ewmh_focus true

xsetroot -cursor_name left_ptr
bspc rule -a floating-terminal state=floating
bspc rule -a feh state=floating
bspc rule -a URxvt state=floating
bspc rule -a Sxiv state=floating
bspc rule -a my-media-player desktop=^10
bspc rule -a Steam desktop=^3 state=pseudo_tiled
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a Wine state=pseudo_tiled
bspc rule -a zoom state=pseudo_tiled desktop=^3
bspc rule -a spotify state=pseudo_tiled rectangle=803x70+0+0
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a jetbrains-idea state=pseudo_tiled

if ! pgrep sxhkd; then
    sxhkd &
else
    pkill -USR1 -x sxhkd
fi

# if ! pgrep polybar
# then
#     for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
#         MONITOR=$m polybar --reload example &
#     done
# fi
#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x lemon && killall lemon
! [ -e ~/.config/lemonbar/lemon ] ||
    [ ~/.config/lemonbar/lemon.rs -ot ~/.config/lemonbar/lemon ] ||
    { rustc ~/.config/lemonbar/lemon.rs -o ~/.config/lemonbar/lemon &&
        echo "compiled" | tee /tmp/compiled_bar; }
bar_args=()
for mon in $(bspc query -M); do
    l() {
        bspc query -T -m "$mon" | jq .rectangle."$1"
    }
    bar_args+=('--bar' "$(l width)x0+$(l x)+$(l y)")
done
~/.config/lemonbar/lemon --tray "${bar_args[@]}" &

sleep 1.5
until bar_id=$(xdo id -a 'bar_of_the_lemons'); do
    sleep 0.001
done
for bar in $bar_id; do
    xdo below -t "$(xdo id -n root)" "$bar"
done
until systray_id=$(xdo id -N 'trayer'); do
    sleep 0.001
done
xdo below -t "$(xdo id -n root)" "$systray_id"
pkill bspswallow || ~/.config/bspwm/bspswallow &
