#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
    test "$(git diff --cached --name-only --diff-filter=A -z "$against" |
        LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

if command -V typos >/dev/null ; then
    if [ -e ".typos.toml" ]; then
        typos || exit 1
    else
        echo "no typos toml, skipping typo checking"
    fi
else
    #shellcheck disable=2016
    echo 'typos checking not installed: `cargo install typos-cli`'
fi

cargo_root=$(find . -name 'Cargo.toml' 2>/dev/null | sort | head -1)
if [ -n "$cargo_root" ]; then
    cd "$(dirname "$cargo_root")" || exit 1
    cargo fmt --check || exit 1
fi

if [ -e mendess-copyright-check-holder ]; then
    holder=$(cat mendess-copyright-check-holder)
    while read -r file; do
        if ! head -n 5 "$file" | grep "Copyright.*$holder" -q; then
            printf "\e[31mERROR:\e[0m %s is missing copyright\n" "$file"
            failed=1
        fi
    done < <(git status --short --no-renames --porcelain --untracked-files=no |
        grep -v '^D' |
        awk '{$1=""; print}' |
        grep -v -E '.*\.md'
    )
    if [ "$failed" ]; then
        exit 1
    fi
fi
