#!/bin/python3

from sys import exit
from subprocess import check_output
import re

acpi = check_output(['acpi', '-b']).decode('utf-8')

if 'rate information unavailable' in acpi:
    exit(1)

p = re.compile(": (\w+), (\d+)")
m = p.search(acpi)
status = m.group(1)
percent = m.group(2)

if status == 'Discharging':
    full_text = ' DIS'
elif status == 'Charging':
    full_text = ' CHR'
else:
    full_text = ' FULL'

print(percent, '%', status)
print(percent, '%', status)

if status == 'Discharging':
    percent = int(percent)
    if percent < 20:
        print("#FF0000")
    elif percent < 40:
        print("#FFAE00")
    elif percent < 60:
        print("FFF600")
    elif percent < 85:
        print("A8FF00")

    if percent < 5:
        exit(33)

exit(0)
