#!/bin/python3

from sys import exit
from subprocess import check_output
import re

acpi = check_output(['acpi', '-b']).decode('utf-8')

if 'rate information unavailable' in acpi:
    exit(1)

p = re.compile(": (\w+), (\d+)%, (\d\d:\d\d)")
m = p.search(acpi)
status = m.group(1)
percent = m.group(2)
time = m.group(3)

if status == 'Discharging':
    status = ' DIS'
elif status == 'Charging':
    status = ' CHR'
else:
    status = ' FULL'

print(percent, '%', status, "({})".format(time))
print(percent, '%', status, "({})".format(time))

if status == ' DIS':
    percent = int(percent)
    if percent < 20:
        print(r"#FF0000")
    elif percent < 40:
        print(r"#FFAE00")
    elif percent < 60:
        print(r"#FFF600")
    elif percent < 85:
        print(r"#A8FF00")

    if percent < 5:
        exit(33)

exit(0)
