#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#DIR="${BLOCK_INSTANCE:-$HOME}"
#ALERT_LOW="${1:-10}" # color will turn red under this value (default: 10%)

free_space () {
    df -h -P -l "$1" | awk '
        /\/.*/ {
        print $4
        exit 0
    }
    '
}

ROOT="$(free_space /)"
Home="$(free_space "$HOME")"

echo "💽" "[/ $ROOT]" "[~ $Home]"
