#!/bin/sh

TRUNC=$(if [ -e /tmp/.bloat ]; then echo '47'; else echo '32'; fi)


CURRENT="$(m current \
    | head -2 \
    | tail -1 \
    | cut -d ':' -f2 \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | cut -c 1-50 \
    | sed -r 's/^(.{'"$TRUNC"'}).*/\1.../')"

[ -z "$CURRENT" ] && exit 0

case $BLOCK_BUTTON in
    1) m prev-file ;;
    2) m pause ;;
    3) m next-file ;;
    4) m vu 5 ;;
    5) m vd 5 ;;
esac

case $(echo '{"command":["get_property","pause"]}' | socat - "$(m socket)" | jq .data -r) in
    true) SIGIL='││' ;;
    false) SIGIL='⊳' ;;
esac

VOL="$(echo '{ "command": ["get_property", "volume"] }' \
    | socat - "$(m socket)" \
    | jq -r .data)"

echo "♪" "$CURRENT" "$SIGIL" "$VOL%"
echo "♪" "$CURRENT" "$SIGIL" "$VOL%"
