#!/bin/sh

# shellcheck source=/home/mendess/Projects/spell-book/spells/library.spell
. library

CURRENT="$(m current \
    | tail -1 \
    | cut -d ':' -f2 \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | cut -c 1-50 \
    | sed -r 's/^(.{47}).*/\1.../')"
[ -z "$CURRENT" ] && exit 0
VOL="$(echo '{ "command": ["get_property", "volume"] }' \
    | socat - "$(mpvsocket)" \
    | jq -r .data)"
echo "♪" "$CURRENT" "@ $VOL%"
echo "♪" "$CURRENT" "@ $VOL%"
